### ISSUE TITLE
Duplicate title on the home page

### ISSUE THREAD

**Issue by castrojo** [ublue-os/website#10]
![image](https://user-images.githubusercontent.com/1264109/218610804-96f4a2e8-82fa-41ca-9811-1933a886d7a2.png)

It'd be nice to remove the duplicate "Universal Blue" from this page

**Comment by castrojo** [comment]
Same on the sidebar: 

![image](https://user-images.githubusercontent.com/1264109/218610978-dd1bc02b-a4f8-4041-8d97-0948fd1c01f0.png)

**Comment by rothgar** [comment]
I don't see this problem when I render locally or on the main site anymore. Probably not an issue.

![image](https://github.com/ublue-os/website/assets/371796/36c92ffd-2a91-49d6-b33e-5b5f851144b8)
