### ISSUE TITLE
ignored images still show up on the images page

### ISSUE THREAD

**Issue by castrojo** [ublue-os/website#148]
https://ublue.it/images/ shows `base-main` and `base-nvidia` despite being on the ignore list.

**Comment by marcoceppi** [comment]
those are not in the ignore list https://github.com/ublue-os/website/blob/main/.github/ublue-scan.yml

**Comment by marcoceppi** [comment]
A PR to update that file in this repo should fix this

**Comment by castrojo** [comment]
Ok the initial image list is `base`, which is included, so does that mean I need explicitly have `base-main` and `base-nvidia`?

**Comment by marcoceppi** [comment]
Yes, it is an exact match
