### ISSUE TITLE
secure boot section

### ISSUE THREAD

**Issue by simon-truhter** [ublue-os/website#186]
```
Secure Boot[¶](https://ublue.it/installation/#secure-boot)

If you choose to install an nvidia variant of ublue-os and have secure boot enabled, the installer will automatically use mokutil to import the ublue-os nvidia module signing key as a Machine Owner Key (MOK) in your UEFI secure boot database.

During the post-install reboot, your system will prompt to verify enrollment of the key.
```
Does the Secure Boot mode needs to be set to "setup" ? at least thats how i remember being able to enroll secure boot keys. 

if so please mention it. if im wrong about this, im sorry for not knowing. i dont have a spare pc currently to test it.

**Comment by Arcitec** [comment]
@simon-truhter No. Setting the BIOS to "Setup mode" will disable Secure Boot and make it await new keys. This is useful if you want to wipe the entire BIOS of all its default keys and only enroll your own corporate keys, for example, to ensure that the computer only boots the corporation's EFI loader.

By default, you don't need to do that. EFI boot uses a Shim signed by Microsoft, which uses the Microsoft key that's already embedded in every computer BIOS.

The Shim in turn is allowed to enroll more keys into your BIOS. So anything you do via `mokutil` gets enrolled via the shim.

In some rare cases, a BIOS could possibly reject keys until you fiddle with the BIOS settings though. For example, on my computer, I think I had to switch from "Standard" to "Custom" key mode in the BIOS. In Standard mode it only allows Microsoft keys and no learning, if I remember correctly. But this could vary in your BIOS.

Either way it will work for you as long as you're able to enter your BIOS to switch a setting if necessary on your computer. In most cases.
