### ISSUE TITLE
Making your own: TOC incomplete

### ISSUE THREAD

**Issue by plata** [ublue-os/website#187]
The table of contents for https://ublue.it/making-your-own/ shows only the first section and subsection. Expectation: Show also "Making your Own" and "Best Practices".

![toc](https://user-images.githubusercontent.com/3973260/235347297-148f73ab-a42e-413b-99f4-43fccc7d8a34.png)

**Comment by EinoHR** [comment]
I believe this is due to the multiple top-level titles (h1). I think just making _purpose_ a h2 would work.
