### ISSUE TITLE
Making your own: add local build instructions

### ISSUE THREAD

**Issue by plata** [ublue-os/website#188]
https://ublue.it/making-your-own/ should describe how to build and test locally. This is currently in https://github.com/ublue-os/startingpoint/blob/main/CONTRIBUTING.md#building-locally.

Not quite sure what the best way would be:
1. Link to `CONTRIBUTING.md`. 
1. Add a new page to the documentation and link to there from `CONTRIBUTING.md` and "Make your own".

**Comment by plata** [comment]
Is the following the correct way to test locally?
1. Run local registry
```
podman run --replace -d --rm --name local-registry -p 5000:5000 docker.io/library/registry:2
```
2. Allow insecure registry
```
mkdir -p ~/.config/containers
nano ~/.config/containers/registries.conf
```
with
```
[[registry]]
location = "127.0.0.1:5000"
insecure = true
```
3. Push image
```
podman push localhost/<name>:latest 127.0.0.1:5000/<name>:latest
```
4. Rebase
``` 
rpm-ostree rebase ostree-unverified-registry:127.0.0.1:5000/<name>:latest
```
The last step gives "server gave HTTP response to HTTPS client".

**Comment by castrojo** [comment]
Yeah it would make sense to probably have this on it's own page. But there's configs in here: https://github.com/ublue-os/forge

More info here: https://github.com/orgs/ublue-os/discussions/120

**Comment by plata** [comment]
I can create a PR with a new page for this.
