### ISSUE TITLE
docs: nvidia "Verification" section is not shown as section

### ISSUE THREAD

**Issue by plata** [ublue-os/website#191]
on https://ublue.it/images/nvidia/:
![section](https://user-images.githubusercontent.com/3973260/235372526-dbd8433a-5ff5-43ce-98fb-fdf896159aa5.png)

**Comment by EinoHR** [comment]
I believe these pages get ingested from [Github README](https://github.com/ublue-os/nvidia)s, but this issue is not present there. This might be one of those MkDocs inconsistensies with Markdown rendering, like requiring a certain level of indentation in sublists.

**Comment by plata** [comment]
Looks like the PR didn't solve the problem.

**Comment by EinoHR** [comment]
> Looks like the PR didn't solve the problem.

Works on my end.

**Comment by plata** [comment]
Yes, works. Probably just wasn't updated yet when I checked.
