### ISSUE TITLE
docs: local testing fails when trying multiple times

### ISSUE THREAD

**Issue by plata** [ublue-os/website#227]
When trying to rebase to "name:latest" multiple times, it complains that the old and new ref are identical. Docs should be updated with instructions how to avoid that.

**Comment by bigpod98** [comment]
Why rebase multiple times, of course if image you are rebasing to and image you have are identical there is no need to rebase to same image?

**Comment by plata** [comment]
It's not really the same. I do changes and push again. Actually, I don't even know why it believes that it's the same. The name is the same but the checksum should be different.

**Comment by bigpod98** [comment]
Well name is the same, you should just upgrade.
Afaik ostree containers when it comes to rebase cares about reference which id a name.

To update to newer version of image (if it has same name and tag) upgrade is it.
Rebase is to switch to a completly differebt ref

**Comment by bigpod98** [comment]
Think of it this way rebase is like git clone while upgrade is like git pull

**Comment by plata** [comment]
Ok. Makes perfect sense now that you explained it. Still need to get used to this.

Do you think others might have the same issue and it's worth including a hint in the docs?
