### ISSUE TITLE
External markdown plugin is broken

### ISSUE THREAD

**Issue by castrojo** [ublue-os/website#246]
See https://ublue.it/images/

Under main, nvidia, etc.

Also I noticed that the git committer's plugin is busted too so maybe there's a build issue like before.

**Comment by alexsch01** [comment]
I just built the website locally and the markdown plugin works, so it really could be a build issue

Python Version: **3.11.2**
OS Version: **Debian 12**
**I used a virtualenv**

I followed these steps

* Setup project dependencies poetry install
* Run the local development server poetry run mkdocs serve
* Open a browser to [localhost:8000](http://localhost:8000/). This will auto-reload on file changes

**Comment by alexsch01** [comment]
Using archive.org, it was supposedly working on May 5 of this year

**Comment by alexsch01** [comment]
@castrojo Fixed in https://github.com/ublue-os/website/commit/f0c3bbf876fe54d155510c6a49e59311ae95c1c5
