### ISSUE TITLE
RSS Page 404 - Not found

### ISSUE THREAD

**Issue by alexsch01** [ublue-os/website#263]
I think the RSS plugin for mkdocs isn't working

I'm getting a 404 error for https://ublue.it/feed_rss_updated.xml

**Comment by alexsch01** [comment]
My testing fork RSS page works: https://alexsch01.github.io/ublue-test/feed_rss_updated.xml

FYI: it isn't using mkdocs-markdown insiders

**Comment by castrojo** [comment]
I think the issue is somewhere in the build as that's not the only plugin that's busted.

**Comment by alexsch01** [comment]
Fixed in https://github.com/ublue-os/website/commit/f0c3bbf876fe54d155510c6a49e59311ae95c1c5
