### ISSUE TITLE
Create a "cheatsheet" page with common system commands

### ISSUE THREAD

**Issue by castrojo** [ublue-os/website#305]
The upstream documentation is so scattered, but we don't need full docs. 

Rolling back, rebasing, pinning, need to be documented with the oci method, we could put a little nvidia section in there, etc. And then maybe some recommendations on how to manage your pins, like (I like to keep the last major kernel version pinned). We type these in discord every day so we might as well. 

Here's the upstream one. I don't even think it needs to be a PDF, we could do universal-blue.org/cheatsheet 

https://docs.fedoraproject.org/en-US/fedora-silverblue/_attachments/silverblue-cheatsheet.pdf

**Comment by storyaddict** [comment]
If we can use these comments to include all the commands we want covered, I'll write it up.

**Comment by storyaddict** [comment]
Good things to add to this would be:

- distrobox commands
- adding/enabling aur in arch containers.

**Comment by nicknamenamenick** [comment]
Agreed on Distrobox commands.  At least the general ones or integrate Ublue's `just` recipes into it.  Would also link Distrobox's documentation in my opinion too since they show a lot of different examples.
