### ISSUE TITLE
Add legacy version (470) to the Nvidia image list

### ISSUE THREAD

**Issue by xalt7x** [ublue-os/website#342]
Commit [feat: Add Nvidia 470xx support (#48) ](https://github.com/ublue-os/nvidia/commit/6d4afbc59dbc278065b7a1b483411b2dc39c347a) introduced support for legacy Geforce 600/700 cards (Kepler) with special image "-470" (e.g. silverblue-nvidia:38-470) . However it's not mentioned on the [image list](https://universal-blue.org/images/#image-list)
So inexperienced user will try to install regular image (e.g. silverblue-nvidia:latest) but since it provides incompatible driver version (e.g. 535) system won't use it.
Actually I've managed to find a hint on the ["images/nvidia"](https://universal-blue.org/images/nvidia/#support) page which helped me to properly rebase image.
 |     | 535xx series (latest, best supported) | 530xx series (deprecated) | 470xx series (Kepler 2012-2014 support) |
   |-----|---------------------------------------|---------------------------|-----------------------------------------|
   | F37 | :37 / :37-535 / :37-current |                           | :37-470                                 |
   | F38 | :latest / :38 / :38-535 / :38-current           | :38-530                   | :38-470                                 |

But it wasn't really obvious and required some time for "digging".

IMO, the best solution would be to create some kind of alias for "470" images (e.g. "legacy-kepler").
Meanwhile that "[support](https://universal-blue.org/images/nvidia/#support)" section on the Nvidia readme could be moved somewhere higher on the page

**Comment by castrojo** [comment]
@storyaddict can you investigate this one? Not familiar enough with nvidia to move on this one, thanks!

**Comment by storyaddict** [comment]
They are correct about the incompatibility.  470 is the cutoff for those older cards. I'll take a look at how and where to make this clearer.
