### ISSUE TITLE
[Membership Request] nicknamenamenick

### ISSUE THREAD

**Issue by castrojo** [ublue-os/website#480]
I'd like to nominate @nicknamenamenick for write status in ublue-os/website. They've done multiple bazzite blog posts and a significant amount of work on the project's documentation over the course of the last few months. 

The project's documentation has significantly improved due to these contributions, so let's power up. 

cc @ublue-os/approver

**Comment by KyleGospo** [comment]
+1

**Comment by Daredevil3869** [comment]
I appreciate all the work gone into ublue and the images a long with it esp bazzite and the bazzite buzzes are really well put together and help keep me informed

**Comment by bsherman** [comment]
+1

**Comment by gerblesh** [comment]
+1

**Comment by castrojo** [comment]
Ok, invite in your inbox, thanks!
