### ISSUE TITLE
remove the "rpm-ostree" commands from Distrobox images

### ISSUE THREAD

**Issue by firefoxlover** [ublue-os/website#530]
I see the Distrobox images are not to be used as system, but as Distrobox containers. 

I guess the creation command is somewhat automatic, but it should be changed to 

```
distrobox create NAME -i URL
```

**Comment by castrojo** [comment]
Yeah we need to filter out the distroboxes from the image list. Here's the exclude list if someone wants to update it: https://github.com/ublue-os/website/blob/main/.github/ublue-scan.yml

**Comment by firefoxlover** [comment]
so the first step is done, but it would be great to have these images listed somewhere else.

That amdgpupro Distrobox image is sick!

**Comment by castrojo** [comment]
Yeah, we have a page just for the toolboxes here: https://universal-blue.org/toolboxes/

But it fell behind rather quickly. We should maybe look at a way to generate ones in there since the boxes have the right tags in them for us to filter them out.
