### ISSUE TITLE
Document SELinux limitations

### ISSUE THREAD

**Issue by plata** [ublue-os/website#627]
Due to limitations in `ostree commit`, custom SELinux labels will not be set as expected e.g. when installing greetd or waydroid during build time (see https://github.com/ublue-os/main/issues/223). This just happens silently and causes issues at runtime which is a pain to figure out later on.

 There should be a warning (maybe on https://universal-blue.org/tinker/modification/?) about this which could also include the currently known packages with issues.

**Comment by akdev1l** [comment]
This is a great idea.

**Comment by m2Giles** [comment]
Strongly agree with this. There is a lot of things that silently break or flat out won't work with SELinux. A few callouts would be highly beneficial for getting people on the right path of workarounds.
