### ISSUE TITLE
Remove Images Section

### ISSUE THREAD

**Issue by noelmiller** [ublue-os/website#712]
It is my opinion that this [section](https://universal-blue.org/images/) should be removed from the main site. It creates confusion and we really should be pushing folks towards using our main downstream projects which are Bluefin, Bazzite, and Ucore (and any other downstreams we intend to adopt).

Having folks rpm-ostree rebase from silverblue is not something we are recommending anymore anyway.

**Comment by castrojo** [comment]
+1!

**Comment by bsherman** [comment]
Is this a `proposal`? ;-)

**Comment by xynydev** [comment]
To provide a differing opinion: I think the base images are also valuable to use directly for end users who don't want all the cool custom things about Bazzite or Bluefin etc., so documentation for installing or rebasing to them should probably exist somewhere.

**Comment by noelmiller** [comment]
> To provide a differing opinion: I think the base images are also valuable to use directly for end users who don't want all the cool custom things about Bazzite or Bluefin etc., so documentation for installing or rebasing to them should probably exist somewhere.

I think the intention is for us to have documentation for how create your own image from one of the base images from a template repo (like we discussed in the Starting Point split). This should avoid the confusion of folks using base images in the first place. I don't think base images should be one of the main things promoted on the site personally.

**Comment by KyleGospo** [comment]
+1

**Comment by castrojo** [comment]
Let's get the ISOs in shape, tested and announced so that the call to action is clear and upfront. I'll work on this the next few days. Let's timebox this to say, sunday the 25th? That way we can merge the startingpoint migration and this cleanup in one go?

**Comment by castrojo** [comment]
Ok I pushed a draft PR that does what I think we want, feedback accepted!

**Comment by castrojo** [comment]
Merging, I've also archived ublue-os/image-scanner-md

**Comment by bsherman** [comment]
>  I've also archived ublue-os/image-scanner-md

Well, now I'm glad I didn't find time to fix it up. :-)
