### ISSUE TITLE
Add a downloads page

### ISSUE THREAD

**Issue by castrojo** [ublue-os/website#88]
We can either add ISO links to the existing images page or we could generate a /downloads/ page that is just all of the ISOs and hashes across the org in one-big-page.

**Comment by EinoHR** [comment]
That's something I had envisioned for the custom frontpage, too (which ik yall haven't exactly picked up on)
https://ublue-images-demo.netlify.app/
I think it'd be totally possible to generate the ISO download links if they are hosted on github releases or smth with naming consistent with the image names. That could entirely retire the rebase command generation.
